### ISSUE TITLE
It does not work for me on windows 10 pro

### ISSUE THREAD

**Issue by arkanmgerges** [pashkatrick/Plumber#17]
Hi,
I've tried to install your app but it always shows this message (I attached a screenshot, to show the message and also to let you know that the api is running)

![image](https://user-images.githubusercontent.com/7836805/120044059-c496de80-c015-11eb-977e-ef0813936874.png)

**Comment by pashkatrick** [comment]
@arkanmgerges thank you for issue, will repair it as soon as fresh release

**Comment by pashkatrick** [comment]
@arkanmgerges now you can test with download pre-release new version of Plumber. 
It's [here](https://github.com/pashkatrick/Plumber/releases/tag/2.0.0). There is no docker dependency now. 
If you'll feel bad about new version - pls give me a feedback via issues. Thanks a lot
